spring:
  application:
    name: scheduler
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 40
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
